Added functionality in line with ticket Bug #11403 Nagios module - review/bug fixes

diff --git a/nagios-plugin/check_drupal b/nagios-plugin/check_drupal
--- a/nagios-plugin/check_drupal
+++ b/nagios-plugin/check_drupal
@@ -9,15 +9,24 @@
 ECHO="/bin/echo"
 GREP="/bin/egrep"
 RM="/bin/rm"
+CP="/bin/cp"
 WGET="/usr/bin/wget"
+SSL=/bin/false
 
 PROGNAME=`/usr/bin/basename $0`
 PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
 REVISION=`echo '$Revision$' | sed -e 's/[^0-9.]//g'`
 
-temp=/tmp/$PROGNAME.$$
+temp=`mktemp`
 
-. $PROGPATH/utils.sh
+if [[ -e $PROGPATH/utils.sh ]]; then
+  . $PROGPATH/utils.sh
+elif [[ -e /usr/lib/nagios/plugins/utils.sh ]]; then
+  . /usr/lib/nagios/plugins/utils.sh
+else
+  echo 'Could not find nagios utils include file!'
+  exit 1
+fi
 
 print_usage() {
   $ECHO "Usage: $PROGNAME -U unique_id [ -H host_name ] [ -P path_to_nagios_status_page ] [ -t time_out_seconds ]"
@@ -76,10 +85,21 @@ while test -n "$1"; do
       path=$2
       shift
       ;;
+    -S)
+      SSL=/bin/true
+      ;;
     -t) 
       timeout=$2
       shift
-            ;;
+      ;;
+    --http-user) 
+      httpuser=$2
+      shift
+      ;;
+    --http-password) 
+      httppassword=$2
+      shift
+      ;;
     *)
       $ECHO "Unknown argument: $1"
       print_usage
@@ -109,10 +129,23 @@ if [ "$unique_id" = "" ]; then
 fi
 
 
-CMD="$WGET -S -T $timeout -O - -U $unique_id http://$hostname/$path"
+if $SSL; then
+  CMD="$WGET --no-check-certificate -S -T $timeout -O - --http-user=$httpuser --http-password=$httppassword -U $unique_id https://$hostname/$path"
+else
+  CMD="$WGET -S -T $timeout -O - -U $unique_id http://$hostname/$path"
+fi
 
 $CMD > $temp 2>&1
 RC=$?
+
+# When using http authentication wget always waits until it receives a 401 before sending the password. 
+# Therefore the first header should be stripped off
+if [ "$httppassword" != "" ]; then
+  temp2=`mktemp`
+  $GREP -v 'HTTP/1.1 401 Authorization Required' $temp > $temp2
+  $CP $temp2 $temp
+  $RM -f $temp2
+fi
 
 HTTP=`$GREP "HTTP/1" $temp`
 
