Synching HEAD with 6.x

diff --git a/nagios-plugin/check_drupal b/nagios-plugin/check_drupal
--- a/nagios-plugin/check_drupal
+++ b/nagios-plugin/check_drupal
@@ -1,13 +1,11 @@
-#! /bin/bash
+#!/bin/bash
 #
-# Drupal monitoring for Nagios
-# Written by Khalid Baheyeldin http://2bits.com
+# Drupal monitoring plugin for Nagios
 #
-# Usage: ./check_drupal -u user_agent string [ -p path_to_nagios_status_page ]
+# Requires a Drupal module from http://drupal.org/project/nagios
 #
-# Paths to commands used in this script.  These may have to be modified to match
-# your system setup.
-
+# Copyright 2009 Khalid Baheyeldin http://2bits.com
+#
 ECHO="/bin/echo"
 GREP="/bin/egrep"
 RM="/bin/rm"
@@ -17,87 +15,82 @@ PROGNAME=`/usr/bin/basename $0`
 PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
 REVISION=`echo '$Revision$' | sed -e 's/[^0-9.]//g'`
 
+temp=/tmp/$PROGNAME.$$
+
 . $PROGPATH/utils.sh
 
 print_usage() {
-    $ECHO "Usage: $PROGNAME -u user_agent_string [ -p path_to_nagios_status_page ]"
-    $ECHO "Usage: $PROGNAME --help"
-    $ECHO "Usage: $PROGNAME --version"
+  $ECHO "Usage: $PROGNAME -U unique_id [ -H host_name ] [ -P path_to_nagios_status_page ] [ -t time_out_seconds ]"
+  $ECHO "Usage: $PROGNAME --help"
+  $ECHO "Usage: $PROGNAME --version"
 }
 
 print_help() {
-    print_revision $PROGNAME $REVISION
-    $ECHO ""
-    print_usage
-    $ECHO ""
-    $ECHO "Drupal monitoring plugin for Nagios"
-    $ECHO ""
-    support
+  print_revision $PROGNAME $REVISION
+  $ECHO ""
+  print_usage
+  $ECHO ""
+  $ECHO "Drupal monitoring plugin for Nagios"
+  $ECHO ""
+  support
 }
 
 # Make sure the correct number of command line
 # arguments have been supplied
-
-#DEBUG=/tmp/nagios.tmp
-#> $DEBUG
-
-#echo "args: $*" >> $DEBUG
-
 if [ $# -lt 1 ]; then
-    print_usage
-    exit $STATE_UNKNOWN
+  print_usage
+  exit $STATE_UNKNOWN
 fi
 
 # Grab the command line arguments
 
-exitstatus=$STATE_WARNING #default
+exitstatus=$STATE_WARNING
 
 while test -n "$1"; do
-    case "$1" in
-        --help)
-            print_help
-            exit $STATE_OK
+  case "$1" in
+    --help)
+      print_help
+      exit $STATE_OK
+      ;;
+    -h)
+      print_help
+      exit $STATE_OK
+      ;;
+    --version)
+      print_revision $PROGNAME $REVISION
+      exit $STATE_OK
+      ;;
+    -V)
+      print_revision $PROGNAME $REVISION
+      exit $STATE_OK
+      ;;
+    -H)
+      hostname=$2
+      shift
+      ;;
+    -U)
+      unique_id=$2
+      shift
+      ;;
+    -P)
+      path=$2
+      shift
+      ;;
+    -t) 
+      timeout=$2
+      shift
             ;;
-        -h)
-            print_help
-            exit $STATE_OK
-            ;;
-        --version)
-            print_revision $PROGNAME $REVISION
-            exit $STATE_OK
-            ;;
-        -V)
-            print_revision $PROGNAME $REVISION
-            exit $STATE_OK
-            ;;
-        -H)
-            hostname=$2
-            shift
-            ;;
-        -u)
-            useragent=$2
-            shift
-            ;;
-        -p)
-            path=$2
-            shift
-            ;;
-        -T) 
-            timeout=$2
-            shift
-            ;;
-        *)
-            $ECHO "Unknown argument: $1"
-            print_usage
-            exit $STATE_UNKNOWN
-            ;;
-    esac
-    shift
+    *)
+      $ECHO "Unknown argument: $1"
+      print_usage
+      exit $STATE_UNKNOWN
+  esac
+  shift
 done
 
 # Set a default for hostname
 if [ "$hostname" = "" ]; then
-  hostname=$NAGIOS_HOSTNAME
+  hostname=$NAGIOS_HOSTADDRESS
 fi
 
 # Set a default for path
@@ -111,34 +104,37 @@ if [ "$timeout" = "" ]; then
 fi
 
 # Set the default for timeout
-if [ "$useragent" = "" ]; then
-  useragent="Nagios"
+if [ "$unique_id" = "" ]; then
+  unique_id="Nagios"
 fi
 
-temp=/tmp/$PROGNAME.$$
 
-CMD="$WGET -T $timeout -O $temp -U $useragent http://$hostname/$path"
+CMD="$WGET -S -T $timeout -O - -U $unique_id http://$hostname/$path"
 
-#echo $CMD >> $DEBUG
-
-$CMD 2> /dev/null
+$CMD > $temp 2>&1
 RC=$?
 
+HTTP=`$GREP "HTTP/1" $temp`
+
 if [ "$RC" != 0 ]; then
-  $ECHO "wget error: $RC: when accessing $hostname/$path"
+  $ECHO "wget error: $RC: when accessing $hostname/$path. HTTP: $HTTP"
   $RM -f $temp
-  exit $STATE_UNKNOWN
+  exit $STATE_CRITICAL
+fi
+
+HTTP_CODE=`$ECHO "$HTTP" | awk '{print $2}'`
+if [ "$HTTP_CODE" != "200" ]; then
+  $ECHO "HTTP returned an error code. HTTP: $HTTP"
+  $RM -f $temp
+  exit $STATE_CRITICAL
 fi
 
 DATA="`$GREP "nagios=" $temp | sed -e 's/^.*nagios=//g'`"
 
-STATUS=`$ECHO $DATA | awk -F, '{print $1}' | sed -e 's/DRUPAL://'`
+STATUS=`$ECHO "$DATA" | awk -F, '{print $1}'`
 
 case $STATUS in
 "OK")
-  exitstatus=$STATE_OK
-  ;;
-"INFO")
   exitstatus=$STATE_OK
   ;;
 "WARNING")
@@ -147,7 +143,7 @@ case $STATUS in
 "UNAUTHORIZED")
   exitstatus=$STATE_CRITICAL
   ;;
-"ERROR")
+"CRITICAL")
   exitstatus=$STATE_CRITICAL
   ;;
 *)
@@ -156,7 +152,7 @@ case $STATUS in
 esac
 
 # Send the data
-$ECHO "$DATA"
+$ECHO "DRUPAL $DATA"
 
 $RM -f $temp
 
